// Support/KeyNameTable.swift
// `airmouse-cli key <name>` name → `AirMouseProtocol.VirtualKey` lookup (spec §3.4.5 `key.code` /
// Appendix §11.2). Generated by hand from `VirtualKey`'s own constant list rather than by the
// `scripts/gen-keycodes.swift` tool (owned by another agent; this table only needs the small set of
// human-typeable names a CLI user would reasonably type, not the full HID table).
import AirMouseProtocol

enum KeyNameTable {
    /// Maps a lowercased key name (as typed on the `key` subcommand) to `(virtual keycode, printable
    /// character)`. `char` is non-nil only for keys the host should be able to re-resolve on its own
    /// input source (spec §5.3.6) — letters, digits, and common punctuation.
    static func lookup(_ name: String) -> (code: UInt16, char: String?)? {
        let key = name.lowercased()
        if key.count == 1, let scalar = key.unicodeScalars.first {
            if let code = letters[key] { return (code, String(scalar)) }
            if let code = digits[key] { return (code, String(scalar)) }
            if let code = punctuation[key] { return (code, String(scalar)) }
        }
        if let code = named[key] { return (code, nil) }
        return nil
    }

    /// All recognized names, for `--help` / error messages.
    static var allNames: [String] {
        (Array(letters.keys) + Array(digits.keys) + Array(punctuation.keys) + Array(named.keys)).sorted()
    }

    private static let letters: [String: UInt16] = [
        "a": VirtualKey.kVK_ANSI_A, "b": VirtualKey.kVK_ANSI_B, "c": VirtualKey.kVK_ANSI_C,
        "d": VirtualKey.kVK_ANSI_D, "e": VirtualKey.kVK_ANSI_E, "f": VirtualKey.kVK_ANSI_F,
        "g": VirtualKey.kVK_ANSI_G, "h": VirtualKey.kVK_ANSI_H, "i": VirtualKey.kVK_ANSI_I,
        "j": VirtualKey.kVK_ANSI_J, "k": VirtualKey.kVK_ANSI_K, "l": VirtualKey.kVK_ANSI_L,
        "m": VirtualKey.kVK_ANSI_M, "n": VirtualKey.kVK_ANSI_N, "o": VirtualKey.kVK_ANSI_O,
        "p": VirtualKey.kVK_ANSI_P, "q": VirtualKey.kVK_ANSI_Q, "r": VirtualKey.kVK_ANSI_R,
        "s": VirtualKey.kVK_ANSI_S, "t": VirtualKey.kVK_ANSI_T, "u": VirtualKey.kVK_ANSI_U,
        "v": VirtualKey.kVK_ANSI_V, "w": VirtualKey.kVK_ANSI_W, "x": VirtualKey.kVK_ANSI_X,
        "y": VirtualKey.kVK_ANSI_Y, "z": VirtualKey.kVK_ANSI_Z,
    ]

    private static let digits: [String: UInt16] = [
        "0": VirtualKey.kVK_ANSI_0, "1": VirtualKey.kVK_ANSI_1, "2": VirtualKey.kVK_ANSI_2,
        "3": VirtualKey.kVK_ANSI_3, "4": VirtualKey.kVK_ANSI_4, "5": VirtualKey.kVK_ANSI_5,
        "6": VirtualKey.kVK_ANSI_6, "7": VirtualKey.kVK_ANSI_7, "8": VirtualKey.kVK_ANSI_8,
        "9": VirtualKey.kVK_ANSI_9,
    ]

    private static let punctuation: [String: UInt16] = [
        "=": VirtualKey.kVK_ANSI_Equal, "-": VirtualKey.kVK_ANSI_Minus,
        "]": VirtualKey.kVK_ANSI_RightBracket, "[": VirtualKey.kVK_ANSI_LeftBracket,
        "'": VirtualKey.kVK_ANSI_Quote, ";": VirtualKey.kVK_ANSI_Semicolon,
        "\\": VirtualKey.kVK_ANSI_Backslash, ",": VirtualKey.kVK_ANSI_Comma,
        "/": VirtualKey.kVK_ANSI_Slash, ".": VirtualKey.kVK_ANSI_Period,
        "`": VirtualKey.kVK_ANSI_Grave,
    ]

    private static let named: [String: UInt16] = [
        "return": VirtualKey.kVK_Return, "enter": VirtualKey.kVK_ANSI_KeypadEnter,
        "tab": VirtualKey.kVK_Tab, "space": VirtualKey.kVK_Space,
        "delete": VirtualKey.kVK_Delete, "backspace": VirtualKey.kVK_Delete,
        "forwarddelete": VirtualKey.kVK_ForwardDelete, "escape": VirtualKey.kVK_Escape,
        "esc": VirtualKey.kVK_Escape, "capslock": VirtualKey.kVK_CapsLock,
        "command": VirtualKey.kVK_Command, "cmd": VirtualKey.kVK_Command,
        "shift": VirtualKey.kVK_Shift, "option": VirtualKey.kVK_Option, "alt": VirtualKey.kVK_Option,
        "control": VirtualKey.kVK_Control, "ctrl": VirtualKey.kVK_Control,
        "fn": VirtualKey.kVK_Function,
        "home": VirtualKey.kVK_Home, "end": VirtualKey.kVK_End,
        "pageup": VirtualKey.kVK_PageUp, "pagedown": VirtualKey.kVK_PageDown,
        "help": VirtualKey.kVK_Help, "insert": VirtualKey.kVK_Help,
        "left": VirtualKey.kVK_LeftArrow, "right": VirtualKey.kVK_RightArrow,
        "down": VirtualKey.kVK_DownArrow, "up": VirtualKey.kVK_UpArrow,
        "f1": VirtualKey.kVK_F1, "f2": VirtualKey.kVK_F2, "f3": VirtualKey.kVK_F3,
        "f4": VirtualKey.kVK_F4, "f5": VirtualKey.kVK_F5, "f6": VirtualKey.kVK_F6,
        "f7": VirtualKey.kVK_F7, "f8": VirtualKey.kVK_F8, "f9": VirtualKey.kVK_F9,
        "f10": VirtualKey.kVK_F10, "f11": VirtualKey.kVK_F11, "f12": VirtualKey.kVK_F12,
        "f13": VirtualKey.kVK_F13, "f14": VirtualKey.kVK_F14, "f15": VirtualKey.kVK_F15,
        "f16": VirtualKey.kVK_F16, "f17": VirtualKey.kVK_F17, "f18": VirtualKey.kVK_F18,
        "f19": VirtualKey.kVK_F19, "f20": VirtualKey.kVK_F20,
    ]
}
